### ISSUE TITLE
Netcat hanging on Debian 10

### ISSUE THREAD

**Issue by jeduardo** [wincent/vim-clipper#4]
When yanking a line, the netcat command hangs and vim hangs with it. Running ps -aux, I can see that the -N switch is not being called for the command. It seems to be caused by a change in the nc command help that no longer displays the word "shutdown" in lowercase, but in uppercase instead:

```ShellSession
$ nc -h 2>&1 | grep -i shutdown
                -N              Shutdown the network socket after EOF on stdin
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by wincent** [comment]
Thanks for the report, and the PR. Going to merge that, but in the meantime note that you can always supply your own command using [`clipper#set_invocation()`](https://github.com/wincent/vim-clipper/blob/acf0296ba3d5d358b415f139bcaf021411ec53fa/doc/clipper.txt#L128-L138) if the autodetection doesn't work.

**Comment by jeduardo** [comment]
Thanks for the hint, will keep this in mind. Also thanks for merging!
